spring:
  application:
    name: volga
  config:
    activate:
      on-profile: dev
  r2dbc:
    url: r2dbc:postgresql://${RDS_HOST}:5432/${POSTGRES_DB}?sslmode=require
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_POOL_ID}
logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:postgresql://postgres_local:5432/${POSTGRES_DB_LOCAL}
    username: ${POSTGRES_USER_LOCAL}
    password: ${POSTGRES_PASSWORD_LOCAL}