spring:
  application:
    name: volga
  config:
    activate:
      on-profile: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/volgadev
    username: user
    password: password
  main:
    web-application-type: reactive
logging:
  level:
    root: INFO