CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cognito_user_id" varchar,
  "house_number" varchar,
  "name" varchar,
  "phone" varchar,
  "email" varchar
);

CREATE TABLE "role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "user_role" (
  "user_id" int,
  "role_id" int
);

CREATE TABLE "reservation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "status_id" int,
  "date" date,
  "start_time" time,
  "end_time" time,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "visit" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "date" date,
  "check_in" timestamp,
  "check_out" timestamp,
  "number_of_people" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "reservation_status_catalog" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE,
  "description" varchar
);

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "reservation" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "reservation" ADD FOREIGN KEY ("status_id") REFERENCES "reservation_status_catalog" ("id");

ALTER TABLE "visit" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
